# Generated by Django 4.2.7 on 2024-03-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_rating_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
